services:
  db:
    image: postgres:12-alpine
    container_name: attendance_db
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - attendancenetwork
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    networks:
      - attendancenetwork
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SECRET_KEY=$SECRET_KEY

networks:
  attendancenetwork:

volumes:
  data: